// tslint:disable
/**
 * Book API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Book
 */
export interface Book {
    /**
     * 
     * @type {number}
     * @memberof Book
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof Book
     */
    title: string;
    /**
     * 
     * @type {Date}
     * @memberof Book
     */
    publishedAt: Date;
}

export function BookFromJSON(json: any): Book {
    return {
        'id': json['id'],
        'title': json['title'],
        'publishedAt': new Date(json['published_at']),
    };
}

export function BookToJSON(value?: Book): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'id': value.id,
        'title': value.title,
        'published_at': value.publishedAt.toISOString().substr(0,10),
    };
}


