// tslint:disable
/**
 * Book API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Book,
    BookFromJSON,
    BookToJSON,
} from './';

/**
 * 
 * @export
 * @interface Books
 */
export interface Books {
    /**
     * 
     * @type {Array<Book>}
     * @memberof Books
     */
    books: Array<Book>;
}

export function BooksFromJSON(json: any): Books {
    return {
        'books': (json['books'] as Array<any>).map(BookFromJSON),
    };
}

export function BooksToJSON(value?: Books): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'books': (value.books as Array<any>).map(BookToJSON),
    };
}


