// tslint:disable
/**
 * Book API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    Books,
    BooksFromJSON,
    BooksToJSON,
} from '../models';

/**
 * no description
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Get all books
     */
    async getBooksRaw(): Promise<runtime.ApiResponse<Books>> {
        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/books`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => BooksFromJSON(jsonValue));
    }

    /**
     * Get all books
     */
    async getBooks(): Promise<Books> {
        const response = await this.getBooksRaw();
        return await response.value();
    }

}
